### ISSUE TITLE
v4.4.0 breaks backwards compatibilty

### ISSUE THREAD

**Issue by dim** [golang-jwt/jwt#183]
After upgrading from 4.3.0 to 4.4.0, my custom implementation of the `Claims` interface is broken:

```
	*Claims does not implement jwt.Claims (wrong type for Valid method)
		have Valid() error
		want Valid(opts ...jwt.validationOption) error
```

**Comment by oxisto** [comment]
Can you share some details about this implementation? Are you embedding `RegisteredClaims` or the old `StandardClaims` (as intended) or are you using your completely own implementation (which is not really intended).

**Comment by dim** [comment]
The implementation was completely custom but I will migrate it to embed `RegisteredClaims` instead.

**Comment by mfridman** [comment]
This is correct, we broke the signature of the interface. We need to revert those set of commits and push a fixed `v.4.5.0` and somehow mark `v.4.4.0` as broken.

**Comment by mfridman** [comment]
Even if when embedding `RegisteredClaims` within a custom type, if that type exposes a `Valid() error` method then it will break the interface. 

I think we should strongly considering backing those changes out.

**Comment by oxisto** [comment]
> Even if when embedding `RegisteredClaims` within a custom type, if that type exposes a `Valid() error` method then it will break the interface.
> 
> I think we should strongly considering backing those changes out.

Hmm good point. In practical use overriding Valid is extremely dangerous and should not be done, but I get the point, that we broke our own promise on compatibility here.

I fear that there is not other way to implement the validation options features then for v4 :(

**Comment by mfridman** [comment]
The use case is projects might want to define their own interfaces for jwt signer/verifier. E.g.,

```go
package authjwt

type Claims interface {
	Valid() error
}

type JWTVerifier interface {
	Verify(token string, dest Claims) error
}
```

Then within the code base these interface are used, and the underlying implementation could be golang-jwt/jwt or something else.

And concrete implementation could look something like this:

```
type CustomClaims struct {
	jwt.RegisteredClaims
        // custom fields
}

// Valid verifies the token is valid.
func (s *SessionClaims) Valid() error {
    // custom validation ..
}
```

**Comment by mfridman** [comment]
> I fear that there is not other way to implement the validation options features then for v4

Indeed, but one of the things I value most is reducing breaking changes within major versions. I also had a panic moment and realized this would break quite a few projects I worked on 😓  .. thankfully resulting in a compile-time error.

I think we can work towards a /v5 with improved ergonomics and re-design the package in such a way that enables more up-front validation options.

Open to suggestions, but I fear we might have _a lot_ of users that rely on the interface (at least in /v4) being stable.

**Comment by mfridman** [comment]
To wrap this up, we've revereted the breaking change and have retracted the `v4.4.0` release in go.mod, note it's still available as a tag/release on GitHub, but the go tooling should ignore this.

Instead, please pull the [release `v4.4.1`](https://github.com/golang-jwt/jwt/releases/tag/v4.4.1)

cc @oxisto Should we re-open an issue to track the original issue, I think it's still valuable? As you previously mentioned, we may not be able to do this in the current /v4, but can think about a more idiotmatic way to do this in a /v5 ?

**Comment by james-d-elliott** [comment]
Realistically you *can* do it in v4 you just have to add a second interface which implements Claims and adds a ValidWithOpts method. Then people who wish to utilize it just need to type assert the Claims to utilize the method.

**Comment by xespona** [comment]
Is what @james-d-elliott suggested something you'd be open to for `v4`? @mfridman
